export default {
    DrawerScreen:{
        key:"DrawerScreen",
        title:""
    },
    DetailScreen:{
        key:"DetailScreen",
        title:""
    },
    FavoritesScreen:{
        key:"FavoritesScreen",
        title:"Favorite"
    },
    HomeScreen:{
        key:"HomeScreen",
        title:"Home"
    },
    HomeAiringScreen:{
        key:"HomeAiringScreen",
        title:"Airing"
    },
    HomeCompleteScreen:{
        key:"HomeCompleteScreen",
        title:"Complete"
    },
    HomeUpComingScreen:{
        key:"HomeUpComingScreen",
        title:"Upcoming"
    }
}
